Repository sparkdotfi/sparklend-advanced, pull requests merged in 2023-12, with the labels that each got.

#6 [SC-242] Remove Stable Logic
  src/VariableBorrowInterestRateStrategy.sol
  test/InterestRateStrategyBase.t.sol
  test/VariableBorrowInterestRateStrategy.t.sol
Labels: Priority: High, Status: Ready for Review

#7 [SC-240] Pot Rate Source
  src/PotRateSource.sol
  src/RateTargetBaseInterestRateStrategy.sol
  src/RateTargetKinkInterestRateStrategy.sol
  src/interfaces/IRateSource.sol
  test/InterestRateStrategyBase.t.sol
  test/PotRateSource.t.sol
  test/SparkDaiMarketInterestRateStrategyIntegration.t.sol
Labels: Priority: Medium, Status: Ready for Review

#8 [SC-241] Refactor Base/Kink Rate Target IRMs
  src/RateTargetBaseInterestRateStrategy.sol
  src/RateTargetKinkInterestRateStrategy.sol
  src/VariableBorrowInterestRateStrategy.sol
  test/InterestRateStrategyBase.t.sol
  test/RateTargetBaseInterestRateStrategy.t.sol
  test/RateTargetKinkInterestRateStrategy.t.sol
  test/SparkDaiMarketInterestRateStrategyIntegration.t.sol
Labels: Priority: Critical, Status: Ready for Review

#9 [SC-298] Adjust README and more integration tests
  README.md
  test/FixedPriceOracleIntegration.t.sol
  test/SparkDaiMarketInterestRateStrategyIntegration.t.sol
  test/SparkLendMainnetIntegration.t.sol
Labels: Priority: Critical, Status: Revisions Needed

#10 chore: Formatting sweep (SC-303)
  README.md
  src/RateTargetBaseInterestRateStrategy.sol
  src/RateTargetKinkInterestRateStrategy.sol
  src/VariableBorrowInterestRateStrategy.sol
  test/SparkLendMainnetIntegration.t.sol
Labels: Priority: Critical, Status: Ready for Review

#11 Require that CappedOracle source only supports 8 decimal sources
  README.md
  src/CappedOracle.sol
  test/CappedOracle.t.sol
  test/mocks/PriceSourceMock.sol
Labels: Priority: High, Status: Ready for Review
